[tool.black]
# Much longer than default (88) to avoid too many changes.
line-length = 88
target_version = ['py38', 'py39', 'py310']

[tool.ruff]
# Much longer than default (88) to avoid too many changes.
line-length = 88
target-version = "py38"
